title: Swatantra Singh
logo: "/profile.png?raw=true"
description: > 
  Senior SAP Technical Consultant
    <a href="https://www.linkedin.com/in/swa10tra/">
      
    </a>
theme: jekyll-theme-minimal
