title: Swatantra Singh
logo: "/profile.png?raw=true"
description: > 
  Senior SAP Technical Consultant
     <p align='left'>
      <a href="https://www.linkedin.com/in/swa10tra/">
        <img src="https://images.credly.com/size/680x680/images/60e6a251-6597-49c9-a349-6b24c981e1b9/E_HANAAW_16.png" alt="SAP Certified Development Specialist-ABAP for SAP HANA            2.0" target="_blank" width="100" height="100">
      </a>
    </p>
theme: jekyll-theme-minimal
