title: Swatantra Singh
logo: "img/pic.png?raw=true"
<br>
description: > 
  Senior SAP Technical Consultant
  <br>
     <p align='left'>
      <a href="https://www.linkedin.com/in/swa10tra/">
        <img src="img/174857.png" alt="LinkedIn" width="30" height="30">
      </a>
    </p>
theme: jekyll-theme-minimal
