title: Swatantra Singh
##logo: "/profile.png?raw=true"
description: >
 Senior SAP Technical Consultant
  <br>
  <a href="https://www.linkedin.com/in/swa10tra/">LinkedIn Profile</a>
theme: jekyll-theme-minimal
