title: Swatantra Singh
logo: 
description: > # your text below (remove <br> elements if you don't need line breaks)
Senior SAP Technical Consultant
<a href="https://www.linkedin.com/in/swa10tra/">LinkedIn Profile</a>
theme: jekyll-theme-minimal
