title: Swatantra Singh
logo: >
<p align='middle'>
<img src="img/pic.png" width="100" height="100">
</p>
description: > 
  Senior SAP Technical Consultant
  <br>
     <p align='left'>
      <a href="https://www.linkedin.com/in/swa10tra/">
        <img src="img/174857.png" alt="LinkedIn" width="30" height="30">
      </a>
    </p>
theme: jekyll-theme-minimal
