title: Swatantra Singh
logo: "/profile.png?raw=true"
description: > 
  Senior SAP Technical Consultant
  <br>
     <p align='left'>
      <a href="https://www.linkedin.com/in/swa10tra/">
        <img src="img/174857.png" alt="LinkedIn" width="50" height="50">
      </a>
    </p>
theme: jekyll-theme-minimal
